### ISSUE TITLE
java.lang.NoSuchMethodError when right-clicking a survivalist generator [Closed]

### ISSUE THREAD

**Issue by venya02** [rwtema/extrautilities_old_issues#432]
when I try to inter face with a generator my game shuts down the internal server (not crashes!)

if you want the full error report, just ask and I'll get it for you

(pc specs: 
windows 7 [64 bit]
ram: 4G
java:1.8.0_25)

**Comment by TherminatorX** [comment]
Mod/forge versions?

**Comment by venya02** [comment]
I guss this is pretty important:
mod version: 1.1.0b and 1.1.0a and 1.1.0 (I tried each)
forge: 1.7.10-10.13.2.1240

**Comment by TherminatorX** [comment]
There's a 1.2.0. Did you try using that?

**Comment by venya02** [comment]
not yet..
works with forge:1.7.10-10.13.2.1264
and mod: 1.2.0
thanks TherminatorX
